component = "GWE"
subcomponent = "DISV"
blocknames = [ "options", "dimensions", "griddata", "vertices", "cell2d",]
multipkg = false
stress = false
advanced = false

[block.options.length_units]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "model length units"
description = "is the length units used for this model.  Values can be ``FEET'', ``METERS'', or ``CENTIMETERS''.  If not specified, the default is ``UNKNOWN''."
deprecated = ""

[block.options.nogrb]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "do not write binary grid file"
description = "keyword to deactivate writing of the binary grid file."
deprecated = ""

[block.options.xorigin]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "x-position origin of the model grid coordinate system"
description = "x-position of the origin used for model grid vertices.  This value should be provided in a real-world coordinate system.  A default value of zero is assigned if not specified.  The value for XORIGIN does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
deprecated = ""

[block.options.yorigin]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "y-position origin of the model grid coordinate system"
description = "y-position of the origin used for model grid vertices.  This value should be provided in a real-world coordinate system.  If not specified, then a default value equal to zero is used.  The value for YORIGIN does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
deprecated = ""

[block.options.angrot]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "rotation angle"
description = "counter-clockwise rotation angle (in degrees) of the model grid coordinate system relative to a real-world coordinate system.  If not specified, then a default value of 0.0 is assigned.  The value for ANGROT does not affect the model simulation, but it is written to the binary grid file so that postprocessors can locate the grid in space."
deprecated = ""

[block.options.export_array_ascii]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "export array variables to layered ascii files."
description = "keyword that specifies input griddata arrays should be written to layered ascii output files."
deprecated = ""

[block.options.export_array_netcdf]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = "export array variables to netcdf output files."
description = "keyword that specifies input griddata arrays should be written to the model output netcdf file."
deprecated = ""

[block.options.ncf_filerecord]
type = "record ncf6 filein ncf6_filename"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = true
preserve_case = false
numeric_index = false
longname = ""
description = ""
deprecated = ""

[block.options.ncf6]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "ncf keyword"
description = "keyword to specify that record corresponds to a netcdf configuration (NCF) file."
deprecated = ""

[block.options.filein]
type = "keyword"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "file keyword"
description = "keyword to specify that an input filename is expected next."
deprecated = ""

[block.options.ncf6_filename]
type = "string"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = true
numeric_index = false
longname = "file name of NCF information"
description = "defines a netcdf configuration (NCF) input file."
deprecated = ""

[block.dimensions.nlay]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "number of layers"
description = "is the number of layers in the model grid."
deprecated = ""

[block.dimensions.ncpl]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "number of cells per layer"
description = "is the number of cells per layer.  This is a constant value for the grid and it applies to all layers."
deprecated = ""

[block.dimensions.nvert]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "number of columns"
description = "is the total number of (x, y) vertex pairs used to characterize the horizontal configuration of the model grid."
deprecated = ""

[block.griddata.top]
type = "double"
block_variable = false
valid = []
shape = "(ncpl)"
tagged = true
in_record = false
layered = false
time_series = false
reader = "readarray"
optional = false
preserve_case = false
numeric_index = false
longname = "model top elevation"
description = "is the top elevation for each cell in the top model layer."
deprecated = ""

[block.griddata.botm]
type = "double"
block_variable = false
valid = []
shape = "(ncpl, nlay)"
tagged = true
in_record = false
layered = true
time_series = false
reader = "readarray"
optional = false
preserve_case = false
numeric_index = false
longname = "model bottom elevation"
description = "is the bottom elevation for each cell."
deprecated = ""

[block.griddata.idomain]
type = "integer"
block_variable = false
valid = []
shape = "(ncpl, nlay)"
tagged = true
in_record = false
layered = true
time_series = false
reader = "readarray"
optional = true
preserve_case = false
numeric_index = false
longname = "idomain existence array"
description = "is an optional array that characterizes the existence status of a cell.  If the IDOMAIN array is not specified, then all model cells exist within the solution.  If the IDOMAIN value for a cell is 0, the cell does not exist in the simulation.  Input and output values will be read and written for the cell, but internal to the program, the cell is excluded from the solution.  If the IDOMAIN value for a cell is 1, the cell exists in the simulation.  If the IDOMAIN value for a cell is -1, the cell does not exist in the simulation.  Furthermore, the first existing cell above will be connected to the first existing cell below.  This type of cell is referred to as a ``vertical pass through'' cell."
deprecated = ""

[block.vertices.iv]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = true
longname = "vertex number"
description = "is the vertex number.  Records in the VERTICES block must be listed in consecutive order from 1 to NVERT."
deprecated = ""

[block.vertices.xv]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "x-coordinate for vertex"
description = "is the x-coordinate for the vertex."
deprecated = ""

[block.vertices.yv]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "y-coordinate for vertex"
description = "is the y-coordinate for the vertex."
deprecated = ""

[block.vertices.vertices]
type = "recarray iv xv yv"
block_variable = false
valid = []
shape = "(nvert)"
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "vertices data"
description = ""
deprecated = ""

[block.cell2d.icell2d]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = true
longname = "cell2d number"
description = "is the CELL2D number.  Records in the CELL2D block must be listed in consecutive order from the first to the last."
deprecated = ""

[block.cell2d.xc]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "x-coordinate for cell center"
description = "is the x-coordinate for the cell center."
deprecated = ""

[block.cell2d.yc]
type = "double"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "y-coordinate for cell center"
description = "is the y-coordinate for the cell center."
deprecated = ""

[block.cell2d.ncvert]
type = "integer"
block_variable = false
valid = []
shape = ""
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "number of cell vertices"
description = "is the number of vertices required to define the cell.  There may be a different number of vertices for each cell."
deprecated = ""

[block.cell2d.icvert]
type = "integer"
block_variable = false
valid = []
shape = "(ncvert)"
tagged = false
in_record = true
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = true
longname = "array of vertex numbers"
description = "is an array of integer values containing vertex numbers (in the VERTICES block) used to define the cell.  Vertices must be listed in clockwise order.  Cells that are connected must share vertices."
deprecated = ""

[block.cell2d.cell2d]
type = "recarray icell2d xc yc ncvert icvert"
block_variable = false
valid = []
shape = "(ncpl)"
tagged = true
in_record = false
layered = false
time_series = false
reader = "urword"
optional = false
preserve_case = false
numeric_index = false
longname = "cell2d data"
description = ""
deprecated = ""
