name: CI
on:
  push:
    paths-ignore:
      - '**.md'
      - '.gitignore'
  pull_request:
    branches:
      - main
      - develop
    paths-ignore:
      - '**.md'
      - '.gitignore'
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.32.0
          environments: dev
          activate-environment: true

      - name: Run ruff
        run: pixi run lint
  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.32.0
          environments: dev
          activate-environment: true

      - name: Print package version
        run: python -c "from flopy4 import version; print(version.__version__)"

      - name: Build package
        run: pixi run build

  test:
    name: Test
    needs:
      - build
      - lint
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, macos-12, windows-2022 ]
        python: [ "310", "311", "312" ]
    env:
      GCC_V: 11
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
      
      - name: Install nightly build
        uses: modflowpy/install-modflow-action@v1
        with:
          repo: modflow6-nightly-build

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.32.0
          environments: test${{ matrix.python }}
          activate-environment: true

      - name: Run tests
        run: pixi run test
